[package]
name = "task2"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive"] }
serde = "1.0.228"
walkdir = "2.5.0"
serde_json = "1.0.147"
